#!/usr/bin/env python

from __future__ import print_function

lang = [
"ar",
"ar_AA",
"ar_EG",
"ar_SA",
"ar_SY",
"cs",
"da",
"de",
"de_AT",
"de_DE",
"en_AU",
"en_US",
"es",
"es_CL",
"es_MX",
"es_PY",
"es_VE",
"fi",
"fr",
"hu",
"hy",
"hy_AM",
"id_ID",
"id_ID",
"it",
"ja",
"nl",
"nl_NL",
"pl_PL",
"pt_BR",
"pt_PT",
"ro",
"ru",
"sk",
"sk_SK",
"sv_SE",
"sl",
"ug",
"vi",
"zh_CN",
"zh_HK",
"zh_TW",
]

import os
import sys

if __name__ == '__main__':

    plg_names = []
    if len(sys.argv) == 1:
        for i in iter(os.listdir('.')):
            if os.path.isdir(i) and not i.startswith('.') and i != "common":
                plg_names.append(i)
    else:
        plg_names = sys.argv[1:]

    for plg_name in plg_names:
        if not os.path.exists(plg_name):
            print("{} is not existed".format(plg_name))
            sys.exit()

        for l in lang:
            mo_dir = "{0}/locale/mo/{1}/LC_MESSAGES".format(plg_name, l)
            os.system('mkdir -p {}'.format(mo_dir))
            name = plg_name
            po_path = "{0}/locale/po/{1}/{2}.po".format(plg_name, l, name)
            if os.path.exists(po_path):
                os.system('msgfmt {0} -o {1}/{2}.mo'.format(po_path, mo_dir, name))
            else:
                print("{0} not support {1}".format(name, l))
