#!/usr/bin/python

lang = ["zh_CN", "zh_TW"]

import os
import glob
import sys

if __name__ == '__main__':

    try:
        plg_name = sys.argv[1]
    except IndexError:
        print "./update_po <plg_name>"
        sys.exit()

    if not os.path.exists(plg_name):
        print "{} is not existed".format(plg_name)
        sys.exit()

    for l in lang:
        plg_po_dir = '%s/locale/po/%s' % (plg_name, l)
        pot_path = "{0}/locale/{0}.pot".format(plg_name)

        os.system("mkdir -p %s" % (plg_po_dir))
        os.system("touch %s" % pot_path)

        name = plg_name
        po_path = '%s/%s.po' % (plg_po_dir, name)
        os.system("touch %s" % po_path)

        cmd= "xgettext --from-code=utf-8 -L python -j -o %s %s"\
                % (pot_path, " ".join(glob.glob("{}/*.coffee".format(plg_name))))
        os.system(cmd)

        os.system("msgmerge %s %s > %s/new_%s.po" % (po_path, pot_path, plg_po_dir, l))

        os.system("mv %s/new_%s.po %s" % (plg_po_dir, l, po_path))
